# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/mlcv
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    # This environment tests the newest supported Anaconda release (4.4.0)
    - env: DISTRIB="conda" PYTHON_VERSION="3.6.1" INSTALL_MKL="false"
           NUMPY_VERSION="1.13.3" SCIPY_VERSION="0.19.1"
           CYTHON_VERSION="0.25.2" COVERAGE=false SKIP_TESTS="true"
  allow_failures:
    # allow_failures seems to be keyed on the python version
    # We are using this to allow failures for DISTRIB=scipy-dev-wheels
    # - python: 3.5

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
